name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 0 */3 * *" # Executa a cada 3 dias à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Realizar requisição na API do Supabase para manter o projeto ativo
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            "${{ secrets.SUPABASE_URL }}/rest/v1/"
